### ISSUE TITLE
Font colour makes text indecipherable

### ISSUE THREAD

**Issue by MaharnavS** [bhavberi/IIITH-Resources#1]
OS: iOS 12.1
Browser: Safari

Part of website: ../IIITH-Resources/Non-Academics/Students_Driven_Facebook_Links

Expected behaviour: Text should be easily decipherable
Behaviour experienced: Text is indecipherable because of black font colour on black background 
Recommended changes: Change font colour to white (or maybe issue with pdf viewer)

Reference Resource has been attached
![IMG_CE1486807417-1](https://user-images.githubusercontent.com/77191936/148112034-69f962c3-0ae1-43bd-8d24-8326dc3252fc.jpeg)
.

**Comment by b-beri** [comment]
![image](https://user-images.githubusercontent.com/91713017/148157528-8889e4c1-7b1c-414b-b6eb-85719683ea3d.png)

**Comment by b-beri** [comment]
What would you suggest for it ?
Should I give a link to PDF, to open in a new tab?

**Comment by MaharnavS** [comment]
That would work fine ig.

**Comment by bhavberi** [comment]
Added download file link above PDF-Viewer
